logsBucket: "gs://${PROJECT_ID}-cloud-build-logs"
steps:
  - id: terraform-init
    name: hashicorp/terraform:1.11
    args: ["init"]
    dir: "deployment/terraform"

  - id: terraform-apply
    name: hashicorp/terraform:1.11
    args: ["apply", "-auto-approve"]
    dir: "deployment/terraform"

  - id: build-container
    name: "gcr.io/cloud-builders/docker"
    args: [
            build,
            --tag, "europe-west2-docker.pkg.dev/essencemediacom-technical/containers/ingest:latest",
            --file, "Dockerfile",
            "."
    ]

  - id: push-container
    name: "gcr.io/cloud-builders/docker"
    args: [
            push, "europe-west2-docker.pkg.dev/essencemediacom-technical/containers/ingest",
            "--all-tags"
    ]
